### ISSUE TITLE
zsh: don't promote sourcing completion file

### ISSUE THREAD

**Issue by z0rc** [rsteube/carapace#230]
https://medium.com/@jzelinskie/please-dont-ship-binaries-with-shell-completion-as-commands-a8b1bcb8a0d0

Sourcing completion files in zsh is common antipattern. Regular completion file should contain only code of completion function (source of `_command`), there is no need to declare function itself. Especially there shouldn't be any calls from `compdef`, this breaks completion if you you want to install completion file properly under `$fpath`, where it can be autoloaded on call. Usually it's task for package manager to put `_command` file under correct path.

**Comment by rsteube** [comment]
Yeah, i know that and i disagree. The reason it is discouraged is that shells source the completion eagerly, but that doesn't make binaries providing the completion wrong.
The performance impact is neglectable when shell scripts are loaded lazily which can be seen in [carapace-bin](https://github.com/rsteube/carapace-bin/) which currently inits 140 completions in ~30ms (single invocation) where the actual completion is loaded on the first `<TAB>` (not the best example though as the shell script carapace produces has been reduced to a couple of lines by now).
I am working on a general solution for this at [lazycomplete](https://github.com/rsteube/lazycomplete).

So yes, there is a significant performance penalty sourcing multiple completions eagerly but `fpath` is just one way to get around it and i see it as the shells fault not providing a different way.

Btw. i had added a check for zsh so generally both ways should work (fpath and direct sourcing - havn't tested it for a while though):
```zsh
compquote '' 2>/dev/null && _example_completion
compdef _example_completion example
```

**Comment by rsteube** [comment]
Just tested the `fpath` variant as far as i can see it still works.
Anyway thanks for pointing this out, i was planning to add some documentation regarding this but just didn't get around to it yet.
