### ISSUE TITLE
Alias completion support

### ISSUE THREAD

**Issue by thatsmydoing** [rsteube/carapace#561]
I was looking to add support for git aliases in carapace-bin but I'm hitting a wall. To clarify, I don't want it to be able to autocomplete the names of aliases as git subcommands, but I want it to actually resolve the alias into whatever it is and continue autocompletion from there.

So for example, if I have a git alias `po = push origin`, not only do I want `git p<TAB>` to suggest `git po` but I want `git po <TAB>` to autocomplete branches as if I typed `git push origin <TAB>`. I looked into the docs to and the closest thing that seemed relevant was `PreInvoke` but even then that didn't work when I tried it.

Currently, I'm working around this by resolving the alias in my shell and then calling carapace to complete it but it would be great if this can be built in to carapace itself.

**Comment by rsteube** [comment]
Yes, the shell should be best place for that as it works across every command/engine.
The only thing is that it doesn't work for subcommands but rather peudo-commands on root level.

e.g. in `zsh`:
![2022-09-17-201929_1276x305_scrot](https://user-images.githubusercontent.com/9090290/190871353-b11dcf13-5b78-41c5-afe4-a5a68e5d9fa6.png)

or in `elvish` with [small-word-abbr](https://elv.sh/ref/edit.html#edit:small-word-abbr) (`gpo<SPACE>` is expanded to what you see in the screenshot)
![2022-09-17-204825_1276x305_scrot](https://user-images.githubusercontent.com/9090290/190872127-24ef5c4e-baac-4430-8ac5-c2a1c2340169.png)

*Regarding doing this in carapace:*
`PreInvoke` doesn't work as it is triggered after the command line is parsed and that in itself would need `po` added as subcomand to `git` (root).
Then there is the issue that the alias needs to replaced on the command line as the actual `git` command doesn't know it.
But the completion results from carapace only replace the current word. Although altering more of the command line is possible it would be quite a bit more complicated.

**Comment by thatsmydoing** [comment]
> Yes, the shell should be best place for that as it works across every command/engine.
> The only thing is that it doesn't work for subcommands but rather peudo-commands on root level.

I did actually go from zsh to elvish and I was missing this particular functionality that just works in git's zsh completion. As an aside, abbrs doesn't really do it for me as it's text replacement as opposed to actual aliasing like you have in zsh.

What I actually have now mirrors how zsh handles git aliases in elvish
```
# eagerly load git completion so we can wrap it
eval (carapace git elvish | slurp)
var git-completer-original = $edit:completion:arg-completer[git]

fn gitcomp {|@a|
  if (> (count $a) 1) {
    var cmd = $a[1]
    var rest = $a[2..]
    var @aliases = (git --list-cmds=alias)

    if (has-value $aliases $cmd) {
      var resolved = (git config --get alias.$cmd)
      if (not (str:has-prefix $resolved "!")) {
        var args = [(edit:wordify $resolved) $@rest]

        $git-completer-original git $@args
        return
      }
    }
  }

  $git-completer-original $@a
}

set edit:completion:arg-completer[git] = $gitcomp~
```
but it seems like I shouldn't have to write that for each shell (as is the motivation for carapace-bin)

> An alternative would be a custom command with subcommands (e.g. `g po`) and [embedding the git completion](https://github.com/rsteube/carapace-bin/blob/master/completers/gh_completer/cmd/repo_clone.go#L35). The would need changes to the context (`push origin`) so at the moment wouldn't work with a [spec](https://github.com/rsteube/carapace-spec).

Ah, I think is what I was looking for, thanks for the tip!

**Comment by rsteube** [comment]
Oh, so that's actually a `git` feature. Wan't aware of that.
That should be possible with the embedding approach using the  [`PreRun`](https://github.com/rsteube/carapace-bin/blob/ad97d14b023eb926384e3c778f03ad069aa2c0cc/completers/cargo_completer/cmd/root.go#L43) function in the -[`git_completer`](https://github.com/rsteube/carapace-bin/blob/master/completers/git_completer/cmd/root.go).
AFAIK `git` also supports plugins (e.g. `git-pluginname` binary in PATH), which i haven't had a look at yet.

**Comment by thatsmydoing** [comment]
That is the approach I ended up taking. I've made a PR to add the git alias support to carapace-bin https://github.com/rsteube/carapace-bin/pull/1288

The key was the `bridge.ActionCarapaceBin`. I'll close this ticket then. Thanks for the guidance!
