### ISSUE TITLE
Disable command & flags highlighting by default ?

### ISSUE THREAD

**Issue by maxlandon** [rsteube/carapace#767]
### Request

Currently, the command groups are randomly highlighted, and the flags depending on their type.

Although it's quite (even very) useful for flags (their type might not be obvious even when being described), highlighting can sometimes make the values quite hard to read.
For someone not acquainted with carapace configuration, or for a user not even knowing he is using carapace (that might happen), this is thus hard to configure.

What do you think of disabling this highlighting by default ? And only apply it at configuration parse time ?

### Proposed solution

Only apply randomized highlighting when parsing a configuration (don't initialize the styles struct with those random colors).

**Comment by rsteube** [comment]
The command group highlighting is not random, but based on order of definition and the `carapace.Highlight*` values (which can be configured).
By default these use the standard terminal colors, so it is up to the users theme how this looks.

**Comment by rsteube** [comment]
It's a core feature that should be enabled by default.
The reasoning for people unacquainted with the configuration applies for both variants.

It can be indirectly disabled by setting the style accordingly at the moment
and there will be some more fine-grained control in the future with #539.
