### ISSUE TITLE
nushell has deprecated let-env

### ISSUE THREAD

**Issue by fuhrmannb** [rsteube/carapace#937]
### Current Behavior

Like the issue highlighted in https://github.com/rsteube/carapace-bin/issues/1761, carapace completion should use `$env.` instead of `let-env`

### Expected Behavior

Carapace should set the environment correctly for nushell completion

### Steps To Reproduce

```nushell
> my-cool-cmd _carapace nushell | save --force ~/.cache/my-cool-cmd/init.nu
> source ~/.cache/my-cool-cmd/init.nu
Error: nu::shell::removed_command

  × Removed command: let-env
   ╭─[C:\Users\me\.cache\my-cool-cmd\init.nu:7:1]
 7 │
 8 │ let-env config = {
   · ───┬───
   ·    ╰── 'let-env' has been removed from Nushell. Please use '$env.<environment variable> = ...' instead.
 9 │   completions: {
   ╰────
```

### Version

v0.44.0

### OS

- [X] Linux
- [X] OSX
- [X] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [X] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

**Comment by rsteube** [comment]
Ah, thought I had fixed that already.

Think it's best to just define the completer as function here.
Nushell so far has no common approach to register a custom completer dynamically.
So this code snippet  is only an instruction and not really sourceable.

With the change it can be used like this after sourcing:
```nu
do $my-cool-cmd $spans
do $my-cool-cmd [my-cool-cmd, ""]
```
Adaption to `external_completer` in `config.nu` are done manually though.

If [carapace-bin](https://github.com/rsteube/carapace-bin) is used  the best approach would be to [bridge it using a spec](https://rsteube.github.io/carapace-bin/spec/bridge.html#carapace):
```yaml
name: my-cool-cmd
completion:
  positionalany: ["$_bridge.Carapace([my-cool-cmd])"]
```

**Comment by fuhrmannb** [comment]
Thanks for the quick fix.

However I believe there is still some `let-env` in the Dockerfile, see this [GitHub search](https://github.com/search?q=repo%3Arsteube%2Fcarapace%20let-env&type=code)):

**Comment by rsteube** [comment]
Will have a look at that, thanks.
