### ISSUE TITLE
Configuration / Styling on nushell?

### ISSUE THREAD

**Issue by Elkellympia** [rsteube/carapace#967]
is the carapace configuration and styling possible on nushell yet? if not, why not?

If so, how should i do it? i find the docs pretty confusing and lacking.

**Comment by rsteube** [comment]
Only [elvish], [powershell], [xonsh] and [zsh] have support for colors at the moment.

see https://rsteube.github.io/carapace-bin/style.html
see https://github.com/nushell/reedline/blob/main/src/menu/mod.rs
related https://github.com/rsteube/carapace/pull/546

[Elvish]:https://elv.sh/
[Powershell]:https://microsoft.com/powershell
[Xonsh]:https://xon.sh/
[Zsh]:https://www.zsh.org/

**Comment by rsteube** [comment]
needs https://github.com/nushell/reedline/pull/691

**Comment by rsteube** [comment]
https://www.nushell.sh/blog/2024-02-06-nushell_0_90_0.html
